security:
  jwt:
    secret-key: ${secret_key}
    expiration-time: ${expiration-time}

exchangeratesapi:
  base-url: ${exchangeRateApiBaseUrl}
  api-key: ${api-key}


spring:
  application:
    name: expenseTracker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update